de::backxtar::clevercharge::services::MessageService
Activity de.backxtar.clevercharge.services.MessageService.activity
Current activity.
String de.backxtar.clevercharge.services.MessageService.message
Message to be send.
int de.backxtar.clevercharge.services.MessageService.gravity
Position of the toast.
boolean de.backxtar.clevercharge.services.MessageService.error
Is error message or success message.
de.backxtar.clevercharge.services.MessageService.MessageService(Activity activity, String message, int gravity, boolean error)
MessageService constructor. activity as object message as String gravity as int error as boolean
void de.backxtar.clevercharge.services.MessageService.sendToast()
Send toast to top location.
Referenced by de.backxtar.clevercharge.LoadingScreen.onCreate, de.backxtar.clevercharge.Login.onCreate, de.backxtar.clevercharge.MainActivity.onRequestPermissionsResult.