de::backxtar::clevercharge::data::ChargingStation
int de.backxtar.clevercharge.data.ChargingStation.id
Station ID.
String de.backxtar.clevercharge.data.ChargingStation.operator
Station operator.
String de.backxtar.clevercharge.data.ChargingStation.street
Station street.
String de.backxtar.clevercharge.data.ChargingStation.number
Station number of street.
String de.backxtar.clevercharge.data.ChargingStation.additional
Station additional.
int de.backxtar.clevercharge.data.ChargingStation.postal_code
Station postal code.
String de.backxtar.clevercharge.data.ChargingStation.location
Station location.
String de.backxtar.clevercharge.data.ChargingStation.state
Station state.
String de.backxtar.clevercharge.data.ChargingStation.area
Station area.
double de.backxtar.clevercharge.data.ChargingStation.lat
Station lat.
double de.backxtar.clevercharge.data.ChargingStation.lon
Station lon.
String de.backxtar.clevercharge.data.ChargingStation.installation_date
Station installation date.
double de.backxtar.clevercharge.data.ChargingStation.conn_power
Station connection power.
ModuleType de.backxtar.clevercharge.data.ChargingStation.module_type
Station module type.
int de.backxtar.clevercharge.data.ChargingStation.number_of_connections
Number of connections.
ArrayList<PlugType> de.backxtar.clevercharge.data.ChargingStation.plug_types_1
Station plug types 1.
double de.backxtar.clevercharge.data.ChargingStation.power_1
Station power of plug 1.
String de.backxtar.clevercharge.data.ChargingStation.public_key_1
Plug 1 public key.
ArrayList<PlugType> de.backxtar.clevercharge.data.ChargingStation.plug_types_2
Station plug types 2.
double de.backxtar.clevercharge.data.ChargingStation.power_2
Station power of plug 2.
String de.backxtar.clevercharge.data.ChargingStation.public_key_2
Plug 2 public key.
ArrayList<PlugType> de.backxtar.clevercharge.data.ChargingStation.plug_types_3
Station plug types 3.
double de.backxtar.clevercharge.data.ChargingStation.power_3
Station power of plug 3.
String de.backxtar.clevercharge.data.ChargingStation.public_key_3
Plug 3 public key.
ArrayList<PlugType> de.backxtar.clevercharge.data.ChargingStation.plug_types_4
Station plug types 4.
double de.backxtar.clevercharge.data.ChargingStation.power_4
Station power of plug 4.
String de.backxtar.clevercharge.data.ChargingStation.public_key_4
Plug 4 public key.
double de.backxtar.clevercharge.data.ChargingStation.getDistance()
Get distance between your position and the stations position. distance in as double
References de.backxtar.clevercharge.managers.UserManager.getMyPosition.
Referenced by de.backxtar.clevercharge.data.ChargingStationAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup.
double de.backxtar.clevercharge.data.ChargingStation.getDistance(final double mLat, final double mLon)
Get distance between your marker and the stations position. mLat of marker mLon of marker distance as double
final int de.backxtar.clevercharge.data.ChargingStation.getId()
Get the stations id. id as int
Referenced by de.backxtar.clevercharge.services.PopupService.showPopup.
final String de.backxtar.clevercharge.data.ChargingStation.getOperator()
Get the stations operator. operator as string
Referenced by de.backxtar.clevercharge.data.ChargingStationAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup.
final String de.backxtar.clevercharge.data.ChargingStation.getStreet()
Get the stations street. street as string
Referenced by de.backxtar.clevercharge.data.ChargingStationAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup.
final String de.backxtar.clevercharge.data.ChargingStation.getNumber()
Get the stations number of street. number as string
Referenced by de.backxtar.clevercharge.data.ChargingStationAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup.
final String de.backxtar.clevercharge.data.ChargingStation.getAdditional()
Get the stations additional. additional as string
final int de.backxtar.clevercharge.data.ChargingStation.getPostal_code()
Get the stations postal code. postal code as int
Referenced by de.backxtar.clevercharge.data.ChargingStationAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup.
final String de.backxtar.clevercharge.data.ChargingStation.getLocation()
Get the stations location. location as string
Referenced by de.backxtar.clevercharge.data.ChargingStationAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup.
final String de.backxtar.clevercharge.data.ChargingStation.getState()
Get the stations state. state as string
final String de.backxtar.clevercharge.data.ChargingStation.getArea()
Get the stations area. area as string
final double de.backxtar.clevercharge.data.ChargingStation.getLat()
Get the stations lat position. lat as double
final double de.backxtar.clevercharge.data.ChargingStation.getLon()
Get the stations lon position. lon as double
final String de.backxtar.clevercharge.data.ChargingStation.getInstallation_date()
Get the stations installation date. installation date as date format
final double de.backxtar.clevercharge.data.ChargingStation.getConn_power()
Get the stations connection power. connection power as double
Referenced by de.backxtar.clevercharge.services.PopupService.showPopup.
final ModuleType de.backxtar.clevercharge.data.ChargingStation.getModule_type()
Get the stations module type. module type as enum
Referenced by de.backxtar.clevercharge.services.PopupService.showPopup.
final int de.backxtar.clevercharge.data.ChargingStation.getNumber_of_connections()
Get the stations amount of connections. amount of connection as int
Referenced by de.backxtar.clevercharge.services.PopupService.showPopup.
final ArrayList< PlugType > de.backxtar.clevercharge.data.ChargingStation.getPlug_types_1()
Get the stations plug types. ArrayList of enums
final double de.backxtar.clevercharge.data.ChargingStation.getPower_1()
Get the stations first plug power. power as double
final String de.backxtar.clevercharge.data.ChargingStation.getPublic_key_1()
Get the stations public key for first connection. key as string
final ArrayList< PlugType > de.backxtar.clevercharge.data.ChargingStation.getPlug_types_2()
Get the stations plug types. ArrayList of enums
final double de.backxtar.clevercharge.data.ChargingStation.getPower_2()
Get the stations second plug power. power as double
final String de.backxtar.clevercharge.data.ChargingStation.getPublic_key_2()
Get the stations public key for second connection. key as string
final ArrayList< PlugType > de.backxtar.clevercharge.data.ChargingStation.getPlug_types_3()
Get the stations plug types. ArrayList of enums
final double de.backxtar.clevercharge.data.ChargingStation.getPower_3()
Get the stations third plug power. power as double
final String de.backxtar.clevercharge.data.ChargingStation.getPublic_key_3()
Get the stations public key for third connection. key as string
final ArrayList< PlugType > de.backxtar.clevercharge.data.ChargingStation.getPlug_types_4()
Get the stations plug types. ArrayList of enums
final double de.backxtar.clevercharge.data.ChargingStation.getPower_4()
Get the stations fourth plug power. power as double
final String de.backxtar.clevercharge.data.ChargingStation.getPublic_key_4()
Get the stations public key for fourth connection. key as string