de::backxtar::clevercharge::managers::StationManager
final Comparator<ChargingStation> de.backxtar.clevercharge.managers.StationManager.sortByDistance
Static comparator for sorting recyclerView.
ArrayList<ChargingStation> de.backxtar.clevercharge.managers.StationManager.station_storage
Global station storage.
int de.backxtar.clevercharge.managers.StationManager.range
Static search radius.
static Comparator< ChargingStation > de.backxtar.clevercharge.managers.StationManager.getSortByDistance()
Get comparator for sorting stations by distance. Comparator<ChargingStation>
Referenced by de.backxtar.clevercharge.fragmentsMain.SearchFragment.onCreateView.
static void de.backxtar.clevercharge.managers.StationManager.setStation_list(ArrayList< ChargingStation > station_list)
Setter for container. station_list of station objects
Referenced by de.backxtar.clevercharge.LoadingScreen.onCreate.
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.getStation_list()
Getter for station container. arrayList with station objects
Referenced by de.backxtar.clevercharge.fragmentsMain.SearchFragment.onCreateView.
static int de.backxtar.clevercharge.managers.StationManager.getRange()
Getter for view range. range as int
static void de.backxtar.clevercharge.managers.StationManager.setRange(int range)
Setter for view range. range as int
Referenced by de.backxtar.clevercharge.Login.onCreate.
static int de.backxtar.clevercharge.managers.StationManager.getStationAmount()
Get amount of stations. amount of stations as int
Referenced by de.backxtar.clevercharge.fragmentsMain.HomeFragment.onCreateView.
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.sort(final ModuleType module_type)
Sort by ModuleType module_type as enum new sorted ArrayList<ChargingStations>
Referenced by de.backxtar.clevercharge.fragmentsMain.HomeFragment.onCreateView, de.backxtar.clevercharge.managers.StationManager.sortByFavAndLocal.
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.sort(final double lat, final double lon)
Sort station by radius. lat of centered point lon of centered point new sorted ArrayList<ChargingStation>
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.sortByFavAndLocal()
Only local favorites. new sorted ArrayList<ChargingStation>
References de.backxtar.clevercharge.managers.UserManager.getApi_data, de.backxtar.clevercharge.data.APIResponse.getFavorites, de.backxtar.clevercharge.managers.UserManager.getMyPosition, de.backxtar.clevercharge.managers.StationManager.sort.
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.getFavorites()
Returns a list with favorites. a sorted list only with favorites
References de.backxtar.clevercharge.managers.UserManager.getApi_data, de.backxtar.clevercharge.data.APIResponse.getFavorites.
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.getDefects()
Returns a list with defect stations. a sorted list only with defect stations
References de.backxtar.clevercharge.managers.UserManager.getApi_data, de.backxtar.clevercharge.data.APIResponse.getDefect_stations_map.
Referenced by de.backxtar.clevercharge.managers.StationManager.getLocalDefects.
static ArrayList< ChargingStation > de.backxtar.clevercharge.managers.StationManager.getLocalDefects(final double lat, final double lon)
Returns a list with local defect stations. lat as double lon as double a sorted list only with local defect stations
References de.backxtar.clevercharge.managers.StationManager.getDefects.
static String de.backxtar.clevercharge.managers.StationManager.convertEnum(Context context, ModuleType module_type)
Convert enum into string module_type as enum enum as string