de::backxtar::clevercharge::services::DownloadService
static ArrayList< ChargingStation > de.backxtar.clevercharge.services.DownloadService.getStations()
Docker for station arrayList. array of station objects
References de.backxtar.clevercharge.services.DownloadService.getJson.
Referenced by de.backxtar.clevercharge.LoadingScreen.onCreate.
static APIResponse de.backxtar.clevercharge.services.DownloadService.getResponse(String endpoint, String[] params)
Get response from api for list requests. endpoint as string params as stringArray new APIResponse class
References de.backxtar.clevercharge.services.DownloadService.getJson.
Referenced by de.backxtar.clevercharge.Login.onCreate.
static APIResponse de.backxtar.clevercharge.services.DownloadService.getResponse(String endpoint)
Get response from api for non list requests. endpoint as string new APIResponse class
References de.backxtar.clevercharge.services.DownloadService.getJson.
static ArrayList< Article > de.backxtar.clevercharge.services.DownloadService.getArticles()
Get articles from api. an article arrayList
References de.backxtar.clevercharge.services.DownloadService.getJson.
Referenced by de.backxtar.clevercharge.LoadingScreen.onCreate.
static String de.backxtar.clevercharge.services.DownloadService.getJson(String endpoint)
Download json from api. json data string endpoint api endpoint https://api.aurora-theogenia.de/chargingstations/charging_stations.json
Referenced by de.backxtar.clevercharge.services.DownloadService.getArticles, de.backxtar.clevercharge.services.DownloadService.getResponse, de.backxtar.clevercharge.services.DownloadService.getStations.
static InputStream de.backxtar.clevercharge.services.DownloadService.read(URL url)
Create InputStream with connection timeout (for big files). url api url Configured InputStream object IOException if url is bad or doesn't exist