de::backxtar::clevercharge::data::APIResponse
int de.backxtar.clevercharge.data.APIResponse.response_code
Response code.
String de.backxtar.clevercharge.data.APIResponse.response_msg
Response message.
int de.backxtar.clevercharge.data.APIResponse.user_id
User ID.
String de.backxtar.clevercharge.data.APIResponse.user_name
Username.
String de.backxtar.clevercharge.data.APIResponse.user_email
User mail.
boolean de.backxtar.clevercharge.data.APIResponse.is_dev
Is dev or normal user.
ArrayList<Integer> de.backxtar.clevercharge.data.APIResponse.fav_station_ids
Favorite stations.
HashMap<Integer, String> de.backxtar.clevercharge.data.APIResponse.defect_stations_map
Defect stations with report msg.
ArrayList<Integer> de.backxtar.clevercharge.data.APIResponse.news_read_ids
News marked as read.
int de.backxtar.clevercharge.data.APIResponse.getResponseCode()
Get response code send by api. code as int
int de.backxtar.clevercharge.data.APIResponse.getUserID()
Get users id. userId as int
String de.backxtar.clevercharge.data.APIResponse.getUserNAME()
Get users username. userName as String
String de.backxtar.clevercharge.data.APIResponse.getUserEMAIL()
Get users email. userMail as String
boolean de.backxtar.clevercharge.data.APIResponse.isDEV()
Get users permissions. as bool
ArrayList< Integer > de.backxtar.clevercharge.data.APIResponse.getFavorites()
Get users favorites favorites as ArrayList<Integer>
Referenced by de.backxtar.clevercharge.managers.StationManager.getFavorites, de.backxtar.clevercharge.data.ChargingStationAdapter.getItemViewType, de.backxtar.clevercharge.services.PopupService.showPopup, de.backxtar.clevercharge.managers.StationManager.sortByFavAndLocal.
HashMap< Integer, String > de.backxtar.clevercharge.data.APIResponse.getDefect_stations_map()
Get global defect stations. defect stations as HashMap<Integer, String>
Referenced by de.backxtar.clevercharge.managers.StationManager.getDefects, de.backxtar.clevercharge.data.ChargingStationAdapter.getItemViewType, de.backxtar.clevercharge.services.PopupService.showPopup, de.backxtar.clevercharge.services.ReportService.showPopup.
void de.backxtar.clevercharge.data.APIResponse.setDefect_stations_map(HashMap< Integer, String > defect_stations_map)
Set global defect stations. defect_stations_map as object
ArrayList< Integer > de.backxtar.clevercharge.data.APIResponse.getNews_read_ids()
Get users news. read news as ArrayList<Integer>
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.getItemViewType, de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.