de::backxtar::clevercharge::managers::UserManager
APIResponse de.backxtar.clevercharge.managers.UserManager.api_data
Static APIResponse class.
ArrayList<Article> de.backxtar.clevercharge.managers.UserManager.articles
Static article ArrayList.
LatLng de.backxtar.clevercharge.managers.UserManager.myPosition
Static LatLng for user's location.
SaveStateService de.backxtar.clevercharge.managers.UserManager.saveStateService
Static container for saveStates.
static APIResponse de.backxtar.clevercharge.managers.UserManager.getApi_data()
Get current saved api data. ApiResponse object
Referenced by de.backxtar.clevercharge.managers.StationManager.getDefects, de.backxtar.clevercharge.managers.StationManager.getFavorites, de.backxtar.clevercharge.data.ArticleAdapter.getItemViewType, de.backxtar.clevercharge.data.ChargingStationAdapter.getItemViewType, de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup, de.backxtar.clevercharge.services.ReportService.showPopup, de.backxtar.clevercharge.managers.StationManager.sortByFavAndLocal.
static void de.backxtar.clevercharge.managers.UserManager.setApi_data(APIResponse api_data)
Set ApiResponse data to current data. api_data as object
Referenced by de.backxtar.clevercharge.Login.onCreate.
static ArrayList< Article > de.backxtar.clevercharge.managers.UserManager.getArticles()
Get current articles for landing page. articles as ArrayList<Article>
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder, de.backxtar.clevercharge.fragmentsMain.HomeFragment.onCreateView.
static void de.backxtar.clevercharge.managers.UserManager.setArticles(ArrayList< Article > articles)
Set Articles to ArrayList<Article>. articles as ArrayList<Article> object
Referenced by de.backxtar.clevercharge.LoadingScreen.onCreate.
static LatLng de.backxtar.clevercharge.managers.UserManager.getMyPosition()
Return the users current position. position as LatLng object
Referenced by de.backxtar.clevercharge.data.ChargingStation.getDistance, de.backxtar.clevercharge.managers.StationManager.sortByFavAndLocal.
static void de.backxtar.clevercharge.managers.UserManager.setMyPosition(LatLng myPosition)
Set users current position. myPosition as LatLng object
Referenced by de.backxtar.clevercharge.MainActivity.onLocationChanged.
static SaveStateService de.backxtar.clevercharge.managers.UserManager.getSaveStateService()
Return SaveState. SaveStateService object
static void de.backxtar.clevercharge.managers.UserManager.setSaveStateService(SaveStateService saveStateService)
Set SaveState saveStateService as object