de::backxtar::clevercharge::MainActivity
BottomNavigationView de.backxtar.clevercharge.MainActivity.navigation
Bottom navigation.
FragmentManager de.backxtar.clevercharge.MainActivity.fragmentManager
Fragment manager.
NavigationManager de.backxtar.clevercharge.MainActivity.navigationManager
Navigation manager.
LocationManager de.backxtar.clevercharge.MainActivity.locationManager
Location manager for user's location.
int de.backxtar.clevercharge.MainActivity.LOCATION_REQUEST_CODE
Request code for getting permissions.
void de.backxtar.clevercharge.MainActivity.onCreate(Bundle savedInstanceState)
On create activity. savedInstanceState as object
void de.backxtar.clevercharge.MainActivity.runMain()
Run main method if permissions granted! Permission listener: onRequestPermissionsResult(int, String[], int[])
void de.backxtar.clevercharge.MainActivity.initObjects()
Initialize Objects
boolean de.backxtar.clevercharge.MainActivity.isFragmentInBackstack(String tag)
BackStack check. tag as string yes or no as boolean
boolean de.backxtar.clevercharge.MainActivity.areProvidersEnabled()
Check if any provider is enabled. boolean if some services are activated
void de.backxtar.clevercharge.MainActivity.onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults)
Permission request listener requestCode as int permissions as string array grantResults as int array
References de.backxtar.clevercharge.services.MessageService.sendToast.
void de.backxtar.clevercharge.MainActivity.onLocationChanged(@NonNull Location location)
Listen to location changes. Executed when location has changed. location as object
References de.backxtar.clevercharge.managers.UserManager.setMyPosition.
void de.backxtar.clevercharge.MainActivity.onProviderEnabled(@NonNull String provider)
Listen to provider enabled events. provider as string
void de.backxtar.clevercharge.MainActivity.onProviderDisabled(@NonNull String provider)
Listen to provider disable events. provider as string.
void de.backxtar.clevercharge.MainActivity.onBackPressed()
Disable back button.
static void de.backxtar.clevercharge.MainActivity.updateBadges(int menuItemId, int number)
Update menu badges. menuItemId as int number as int
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder, de.backxtar.clevercharge.services.PopupService.showPopup, de.backxtar.clevercharge.services.ReportService.showPopup.