de::backxtar::clevercharge::data::Article
int de.backxtar.clevercharge.data.Article.id
Article ID.
String de.backxtar.clevercharge.data.Article.category
News category.
String de.backxtar.clevercharge.data.Article.author
News author.
String de.backxtar.clevercharge.data.Article.title
News title.
String de.backxtar.clevercharge.data.Article.description
News description.
String de.backxtar.clevercharge.data.Article.urlToImage
Url to news image.
String de.backxtar.clevercharge.data.Article.publishedAt
Date news was published.
String de.backxtar.clevercharge.data.Article.content
News content.
int de.backxtar.clevercharge.data.Article.getId()
Get news id. id as int
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.
String de.backxtar.clevercharge.data.Article.getCategory()
Get news category. category as String
String de.backxtar.clevercharge.data.Article.getAuthor()
Get news author. author as String
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.
String de.backxtar.clevercharge.data.Article.getTitle()
Get news title. title as String
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.
String de.backxtar.clevercharge.data.Article.getDescription()
Get news description. desc as String
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.
String de.backxtar.clevercharge.data.Article.getUrlToImage()
Get news image-url. url as String
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.
String de.backxtar.clevercharge.data.Article.getPublishedAt()
Get news published date. date as String
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.
String de.backxtar.clevercharge.data.Article.getContent()
Get news content. content as String
Referenced by de.backxtar.clevercharge.data.ArticleAdapter.onBindViewHolder.